### ISSUE TITLE
CRSP-IBES link table

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#10]
WRDS SAS macro keeps the ticker with lower score when using exchange ticker to complete the matching. However, there are four cases as below where the scores are the same. 

For the SAS macro: they sort by ticker and score, and then keep the the first ticker. This can filter out ticker with lower score when the scores are different. But this will randomly select the mathcing if the scores are same.

`11_PrepareLinkingTables.do` requires score not greater than 2. So the only question is the ticker `PD2`. How to choose the matching since they have same score: further check this one or kick this ticker out?

I do not think this will change the empirical results and just for your information.

```
ticker   permno  score
PD2      84155       0
PD2      90999       0
permno 84155 was kept from SAS code

KRE1    65162        5
KRE1    65170        5
permno 65170 was kept from SAS code

CMD1  52652         5
CMD1  63933         5
permno 63933 was kept from SAS code

MP      13135       6
MP      55336       6
permno 55336 was kept from SAS code
```

**Comment by OpenSourceAP** [comment]
Thanks, very useful!

**Comment by OpenSourceAP** [comment]
Have not addressed the issue further since it only concerns very few observations.
