### ISSUE TITLE
Momentum sample start date

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#101]
The signaldoc csv has 1964, but should it be 1965?  Table I of Jegadeesh and Titman 1993 says Jan 1965 - Dec 1989

**Comment by OpenSourceAP** [comment]
Based on footnote 4 in Jegadeesh and Titman (1993), we should not change the start date. Table 1 reports estimate for January 1965 to December 1989 but only because they require a full two-year period for their K=12, J=12 specification. Since we use J=12, K=1, using 1964 as starting year is fine.
