### ISSUE TITLE
Earlier paper for SmileSlope (Yan 2011)

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#102]
We currently cite Yan (2011, JFE) for SmileSlope (Put volatility minus call volatility), but an earlier cite is Bali and Kovakimian (2009, MS). Bali and Kovakimian was also received by the respective journal earlier (April 2008 vs May 2009).  From my recollection, we added Yan to the RAPS paper when we were looking through HLZ for stuff we could easily replicate, and perhaps because we were naively biased in favor of JF, JFE, RFS, we picked up Yan first.  Curiously, Yan doesn't cite Bali and Kovakimian, but it does cite the Xing et al JFQA paper.

Table 3 of Bali and Kovakimian is clear:

![image](https://user-images.githubusercontent.com/65506481/228092050-2f7f47a7-93a4-4189-9354-d533cdeb2f65.png)

It differs from Table 5 of Yan in emphasizing VW instead of EW.   BK also differ in using option expirations between 1 and 3 months, vs 1 month for Yan.  BK also screens to have near-money options rather than Yan's fixing delta at +-0.5.

It's a bit unclear whether we should replace SmileSlope or add a new variable (perhaps ImpliedVolSpread).  My vote is to add ImpliedvolSpread.  Adding is consistent with how we've been handling potentially redundant variables.  It also more fully represents the literature and helps document the details of the peer-review process.

**Comment by AlecErb** [comment]
Now in the code as CPVolSpread (Panel B) and RIVolSpread (Panel A) (d188d86874714fd44a3a5c1cd9f0a1c200d32a3b)
