### ISSUE TITLE
lots of zeros in herf pre 1951

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#107]
I doubt this matters, but we should probably clean it up.  in the early sample, the herf data looks like this: 
![image](https://user-images.githubusercontent.com/65506481/232234565-9d5c11ac-e9b0-4101-8e89-8818725ee8ad.png)

It goes on like this until 1951

![image](https://user-images.githubusercontent.com/65506481/232234617-1a7bb309-8919-4678-84fc-fe5a200af513.png)

The OP starts their sample in 1963, so this shouldn't matter.  

It's most likely that herf should be NA, not zero, in the early sample.  Just something we should check on.

**Comment by tomz23** [comment]
Fixed in f60269d92c17cb7e5aaee535234056f5c387d716
