### ISSUE TITLE
IdioRisk / IdioVolCAPM / IdioVol3F confusion and bugs

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#110]
It's all quite confusing, so let me just say what we _should_ have in our code based off Ang Hodrick Xing Zhang Table VI:

- Panel A: Realized volatility based on daily returns over the past month
-- Right now we lack this variable, though we sometimes use IdioRisk as if it is supposed to be this variable
- Panel B: The volatility of residuals from a regression of daily returns on the FF3 model over the past month
--  We have this variable as IdioVol3F, but it is based off of many regressions (one for each day), the same bug we had with Coskewness back in the day.

This is a non-negligible bug because volatility is often used as an ingredient in other predictors.  In fact we came upon this problem when trying to add Bai-Hovakimian's VRP predictor.

**Comment by chenandrewy** [comment]
Fixed on the patches-2023 branch in this commit: 36722923190bf772dcae2baf01985a404044a0d2

**Comment by AlecErb** [comment]
Merged to master d188d86874714fd44a3a5c1cd9f0a1c200d32a3b
