### ISSUE TITLE
illiquidity construction

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#111]
Is necessary to take into account the minimum number of valid observations when constructing illiquidity? Original paper has this requirement.
> Amihud (2002), p36
> The stock has return and volume data for more than 200 days during year

In **SignalDoc.csv**, the filter is `abs(prc)>5` and the OP also requires `NYSE`. So adding this filter in portoflio code?
> Amihud (2002), p36
> The effect of illiquidity on stock return is examined for stocks traded in the New York Stock Exchange (NYSE)
> ... ...
> Tests are confined to NYSE-traded stocks to avoid the effects of differences in market microstructures

**Comment by chenandrewy** [comment]
Good catch @mk0417!  We'll make the change.  Thanks! Here's a screenshot for ease of reference: 
![image](https://github.com/OpenSourceAP/CrossSection/assets/65506481/ce5180f1-8b28-435f-aa26-7b5f852a0f59)

**Comment by chenandrewy** [comment]
fixed here: 69865cf0d2207a496ff3beaff921a2992df2cf4a
