### ISSUE TITLE
SignalDoc improvement 

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#112]
A small tweak: journal for `MaxRet` should be **JFE** in SignalDoc.csv

**Comment by chenandrewy** [comment]
Yup, totally.  Thanks for this too @mk0417!  We'll make the change.

**Comment by chenandrewy** [comment]
fixed here: 69865cf0d2207a496ff3beaff921a2992df2cf4a

**Comment by mk0417** [comment]
Thank you !!!
