### ISSUE TITLE
MRreversal.do and Mom18m13m.do

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#120]
They should be the same predictor. And it seems there is no **MRreversal** in SignalDoc.

**Comment by chenandrewy** [comment]
On my end, it looks like the error is Mom18m13m.do should be deleted (reundant with MRreversal.do).  I do see MRreversal in SignalDoc (at least in my version).

**Comment by chenandrewy** [comment]
Fixed here: 18ddbabd75d587f8b699808faffce2a635ca5dc3.  Thanks @mk0417 !

**Comment by mk0417** [comment]
Hi @chenandrewy , thank you. You are right. MRreversal is in the list.
