### ISSUE TITLE
Missing Size characteristic?

### ISSUE THREAD

**Issue by shokru** [OpenSourceAP/CrossSection#14]
Thank you for this amazing resource. 
In the Appendix, it is mentioned that the Size factor (from Banz 1981) is available (it is undoubtedly an important one).
However, I fail to find it under its name (Size) in both the base and additional files.
Has the column name changed?
Many thanks!

**Comment by OpenSourceAP** [comment]
Size is an untransformed CRSP variable. Therefore, we can't share it. We should add a note to the documentation somewhere.

**Comment by OpenSourceAP** [comment]
Addressed in updated data documentation
