### ISSUE TITLE
Adjustment of Book Value of Equity when we make FailureProbability 

### ISSUE THREAD

**Issue by SeongDeokKo** [OpenSourceAP/CrossSection#141]
In the code you write, I think you do not adjust the book value of equity ( ceqq in this case). 

In the original paper, the original authors add 
![image](https://github.com/OpenSourceAP/CrossSection/assets/38172169/91522f1c-8e8b-4f0e-94f5-06e81f8de723)

So I think there could be a negative market-to-book ratio in this case. 

gen tempBE = ceqq + 0.1 * (tempMV - ceqq)
replace tempBE = 1 / 1000000  if tempBE < 0  
gen tempMB = tempMV / tempBE
I think such kind of code could fix the problem 

Thank you for reading my request

**Comment by chenandrewy** [comment]
Great catch @SeongDeokKo! We'll fix that in the next release.

For reference, the code for FailureProbability is here: https://github.com/OpenSourceAP/CrossSection/blob/00bafe41dc20783cb2c2a341658134ff86c6b547/Signals/Code/Placebos/ZZ2_FailureProbability_FailureProbabilityJune.do#L4

and the quote is from page 2906 of Campbell, Hilsher and Szlagyi 2008

**Comment by tomz23** [comment]
Fixed in https://github.com/OpenSourceAP/CrossSection/commit/1b91c85c62501bd91b91f4c4057cc74724d4dac3 .

In the same commit, I also updated the book equity definition from `ceqq` to the more involved construction that CHS take from Cohen, Polk, and Vuolteenaho (2003).
