### ISSUE TITLE
Cannot verify t-stat and original table in DivYieldST

### ISSUE THREAD

**Issue by tomz23** [OpenSourceAP/CrossSection#146]
SignalDoc.csv says the t-stat of 6.3 is from a multivariate regression in table 1. I cannot find the corresponding t-stat and table 1 iin any case seems incorrect.

**Comment by chenandrewy** [comment]
I think the existing entry is correct. Here's Table 1 from Litzenberger-Ramaswamy 1979

![image](https://github.com/user-attachments/assets/27415eea-f0a9-4c45-ab6c-017b3b3a093e)

The definition for $d_{it}$ is 

![image](https://github.com/user-attachments/assets/0efbfac1-02b6-490e-b494-5b7df5e80d2c)

@tomz23: does that look right to you?

**Comment by tomz23** [comment]
Shoot, I was thrown off by the reference to the JF in the journal column and mistakenly looked at Litzenberger and Ramaswamy (1982, JF). The 1979 article is in the JFE. I'll fix the entry. 
Thanks for checking!

**Comment by tomz23** [comment]
Fixed signaldoc here: https://github.com/OpenSourceAP/CrossSection/commit/eae8184c502f94d735c8d47072d052298d0a26ed
