### ISSUE TITLE
Oscore.csv data error

### ISSUE THREAD

**Issue by dcgemp** [OpenSourceAP/CrossSection#157]
[OScore.csv](https://github.com/user-attachments/files/16995487/OScore.csv)
In the Oscore.csv file (downloaded on 9/5/24 from the Predictors folder on Google Drive https://drive.google.com/drive/folders/1rQ1VV6pUCXhQhIL1g0WDuXlGsZORyp5E), all of the values for Oscore appear to be either 0 or 1. 

Thank you for checking on this!

**Comment by tomz23** [comment]
That is correct. See code that generates OScore: https://github.com/OpenSourceAP/CrossSection/blob/master/Signals/Code/Predictors/OScore.do
