### ISSUE TITLE
Settle on working directory for Portfolios Code

### ISSUE THREAD

**Issue by OpenSourceAP** [OpenSourceAP/CrossSection#16]

**Comment by OpenSourceAP** [comment]
Addressed in bbc7ae5ad07a52e892f19cd513ba934809dc35ff

**Comment by chenandrewy** [comment]
I think we still need to add something like setwd(paste0(pathProject,'Portfolios/Code/')) near the beginning of master.R

**Comment by chenandrewy** [comment]
I added setwd([etc]).  Hopefully this works.  ec81d3a2
