### ISSUE TITLE
"signed_predictors_dl_wide" data contains a large number of NAN

### ISSUE THREAD

**Issue by Lavender-xlz** [OpenSourceAP/CrossSection#160]
Hello, I'm wondering why there are so many NAN values in the "signed_predictors_dl_wide" data that I downloaded. How did you handle this issue, and how did it affect your research in the paper?
![屏幕截图 2024-12-15 193728](https://github.com/user-attachments/assets/71462ba1-1ad4-4c1d-9784-bbefd25c9858)

**Comment by tomz23** [comment]
See FAQ: https://www.openassetpricing.com/faq/#q-missings
