### ISSUE TITLE
Add R version and detailed R installation instructions to readme?

### ISSUE THREAD

**Issue by OpenSourceAP** [OpenSourceAP/CrossSection#17]

**Comment by OpenSourceAP** [comment]
Added version requirements for R packages as info to code (requirements.txt): https://github.com/OpenSourceAP/CrossSection/commit/a5caacc858188dccce6a83e7493149bc4a914277

**Comment by chenandrewy** [comment]
fcc27fb3d4b0026838fcf36b22e01baeb4d851f8
