### ISSUE TITLE
Field descriptors for SignalBase.csv

### ISSUE THREAD

**Issue by csrvermaak** [OpenSourceAP/CrossSection#2]
Hi Guys

Thank you for a fantastic and fascinating article. 

I have a few questions on the `signalbase.csv` dataset

1. Is `permno` the Key/UniqueID for every company?
1. Which field did you use for the Liquidity filter?

Kind regards

**Comment by JustinMShea** [comment]
Regarding `permno`, this is well documented `CRSP` variable. http://crsp.org/products/documentation/data-definitions-p#permno

**Comment by OpenSourceAP** [comment]
Hi,
yes `permno` uniquely each security (note that, although not super common, a company can have multiple securities (e.g. different share classes) outstanding). 
Liquidity screens are implemented in `23_liqscreens_ConstructPorts.R`: These include a size (market value of equity), a stock exchange (NYSE only) and a share price screen. 
Best,
Tom
