### ISSUE TITLE
Fix "font family not found in Windows font database" in, for example, 31_CheckPredictorsExhibits.R

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#26]

**Comment by OpenSourceAP** [comment]
Font import now part of settings file, added in https://github.com/OpenSourceAP/CrossSection/commit/7aa437c9de9fc34673a669cd68ab800bedb5a062

**Comment by OpenSourceAP** [comment]
Added check for whether font exists, otherwise use defaults, see https://github.com/OpenSourceAP/CrossSection/commit/293614ee454918c4aeec6a9c736d27b07c8394a4
