### ISSUE TITLE
t-stat results data

### ISSUE THREAD

**Issue by firmai** [OpenSourceAP/CrossSection#40]
Is there perhaps a dataset where I can pick up the t-stats with minimal effort, to reconstruct the plots as you have in your paper. Thanks in advance.

**Comment by tomz23** [comment]
We output a [PredictorSummary.xlsx](https://drive.google.com/file/d/1preBTzA8Khh7Dp_cPpyysSxcDUGKfBj6/view) file you can find on GDrive. That file should have all the info that you need. The file is created in https://github.com/OpenSourceAP/CrossSection/blob/master/Portfolios/Code/20_PredictorPorts.R

**Comment by firmai** [comment]
Excellent thanks.
