### ISSUE TITLE
Various Portfolios Quantiles (3,5,10)

### ISSUE THREAD

**Issue by firmai** [OpenSourceAP/CrossSection#42]
Going through the daily returns data, the portfolios are split sometimes 3, 5, 10, was this due to some constraint? 

![image](https://user-images.githubusercontent.com/26666267/121681280-83d9a380-cab2-11eb-887e-b412b37b1cd2.png)

**Comment by chenandrewy** [comment]
For our baseline data, we follow the original paper in how they split stocks into portfolios.  Please see the paper.  But we should add a note to the FAQ.

**Comment by firmai** [comment]
Fascinating, do excuse me for going straight to the repo, it allows to remain somewhat critical by only having access to the code and the data. Do you think it is worth creating daily portfolios with standard quantiles and making that available, I think you do have the necessary data to do that... I mean there is no reason for you to do this, it would just be a nice to have and easier for future researchers to inspect..

**Comment by chenandrewy** [comment]
We provide standardized quantiles too.  Please see the Data release notes.

**Comment by chenandrewy** [comment]
We added an explanation for the variation in portfolio counts here https://www.openassetpricing.com/faq/#q-port
