### ISSUE TITLE
Daily Returns Statistics

### ISSUE THREAD

**Issue by firmai** [OpenSourceAP/CrossSection#43]
STreversal Daily data compounded returns, turns a dollar into a few billion dollars (all the other anomalies are squeezed to the bottom in a normal range, I am wondering if STreversal, IndRetBig, and IntMom might not have some data error. 

![image](https://user-images.githubusercontent.com/26666267/121690230-8097e500-cabd-11eb-9fd3-9a25e9b52ef8.png)

**Comment by firmai** [comment]
This updated logged graph might show a better picture 

![image](https://user-images.githubusercontent.com/26666267/121692125-aaeaa200-cabf-11eb-839f-4bcc8b9ab1b2.png)

**Comment by firmai** [comment]
I have noticed that squares at the start comes from data that is not entirely clean: 

![image](https://user-images.githubusercontent.com/26666267/121693608-357fd100-cac1-11eb-86c1-451356bf5496.png)

**Comment by chenandrewy** [comment]
I looked into this for about 30 min, and it seems STreversal simply stands out in its mean return and the number of obsrevations in the data.  The cumulative return \approx (1+mean return)^[number of obs] so you get these nutty numbers for STreversal.  If you read in PredictorSummary.xlsx as summary, you get this:
  
![image](https://user-images.githubusercontent.com/65506481/122288967-2e413480-cec0-11eb-9eb9-a57e57efff8a.png)

It's also unlikely that STreversal has an error.  Don't get me wrong, it's possible.  But these crazy cumulative returns are there in both the monthly and daily data we produce, so it's not likely an issue with the portfolio code.  Then the signal code for STreversal is just one line.  

![image](https://user-images.githubusercontent.com/65506481/122289431-b4f61180-cec0-11eb-9a8d-14145ab570a9.png)

https://github.com/OpenSourceAP/CrossSection/blob/master/Signals/Code/Predictors/STreversal.do

On the "squares," I'm not sure what you're talking about, but it seems like PS is miscategorized as continuous.   The original signal is discrete.  This is the original table:

![image](https://user-images.githubusercontent.com/65506481/122290339-a3613980-cec1-11eb-9f43-6b0c555d0c52.png)

Could you please open a new issue for this "squares issue?"  Thanks! -Andrew
