### ISSUE TITLE
tstk not found in B_CompustatAnnual.do

### ISSUE THREAD

**Issue by adlerzhou** [OpenSourceAP/CrossSection#46]
At line 64, the code set the tstk to zero is missing. But in the requesting step (line 17), only tstkp is requested.

**Comment by tomz23** [comment]
It's kind of a Stata quirk: In Stata this works because Stata finds the variable `tstkp` when you just type `tstk` (as there's no other variable in the dataset that starts with `tstk`).

**Comment by OpenSourceAP** [comment]
Updated in https://github.com/OpenSourceAP/CrossSection/commit/9aff1de146059292103ac6a396ad7f0e0235834b
