### ISSUE TITLE
Random order issue

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#48]
I am not sure if my understanding here is correct or not. So could you please see my question below? Thanks in advance.

There might be a random order issue about the code block in line 35 to 40 from **Signals/Code/DataDownloads/C_CompustatQuarterly.do**.

```Stata
// Prepare year-to-date items
sort gvkey fyearq fqtr
foreach v of varlist sstky prstkcy oancfy fopty {
    gen `v'q = `v' if fqtr == 1
    by gvkey fyearq: replace `v'q = `v' - `v'[_n-1] if fqtr !=1
}
```
There are some observations with the same `gvkey`, `fyearq` and `fqtr`. In those cases, the order will be random (see page 2 via this link: https://www.stata.com/manuals/dsort.pdf). So the calculation might not always use the most recent information.

When sorting by `gvkey`, `fyearq` and `fqtr`, the following example can happen:
|gvkey	|datadate	      |fyearq    |fqtr  |oancfy |oancfyq|
|---------|-------------|--------|-----|-------|---------|
|001444	|31mar2004   |2004    |1	    |-1.503	 |-1.503|
|001444	|31oct2003    |2004    |1	    |-.736	 |-.736|
|001444	|30jun2004   |2004	    |2	    |-3.315	 |-2.579|

For gvkey 001444 on 30jun2004, `oancfyq` is  -2.579 which is -3.315 (30jun2004)+0.736 (31oct2003). 

Below should make sure the order is correct.
```Stata
sort gvkey fyearq fqtr datadate
foreach v of varlist sstky prstkcy oancfy fopty {
    gen `v'q = `v' if fqtr == 1
    by gvkey fyearq (fqtr datadate): replace `v'q = `v' - `v'[_n-1] if fqtr !=1
}
```

**Comment by OpenSourceAP** [comment]
Thanks, good catch! I checked and it seems to affect around 700 observations out of 1.6m, so I don't expect it to have an effect on results. I'll update the code to be unambiguous though.

**Comment by OpenSourceAP** [comment]
https://github.com/OpenSourceAP/CrossSection/commit/96b6bf91e57e1bf8c712b38d3cd5618b9521cec9
