### ISSUE TITLE
FRED data

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#5]
Thanks for your project and very appreciate your work to make it open source.

Can I ask which package are you using to extract FRED data? Is this one as below?
https://github.com/sboysel/fredr

If so, there is an open issue for this package: https://github.com/sboysel/fredr/issues/75

`install.packages("fredr")` is currently not working and should install this package from github: `devtools::install_github("sboysel/fredr")`

**Comment by matiarj** [comment]
Second this I'm also getting this same error.

**Comment by OpenSourceAP** [comment]
Thanks for pointing that out. We will add it to the documentation.

**Comment by JustinMShea** [comment]
Just add the package version number in a comment and you're good to go.

**Comment by matiarj** [comment]
and a quick library(fredr) at the top. Thank you again!

**Comment by OpenSourceAP** [comment]
Moved FRED downloading to Stata in the new release d1e4e4d1c08784d2cb8fe1202f772581ec33b66d
