### ISSUE TITLE
VOLUME in Corwin_Schultz_Edit.sas

### ISSUE THREAD

**Issue by xiaoqyaoyao** [OpenSourceAP/CrossSection#55]
There should be a sentence 'VOLUME=vol;' in the first block code. Otherwise, VOLUME is uninitialized.

**Comment by chenandrewy** [comment]
Thanks @xiaoqyaoyao.  We'll take a look when we update in a couple months.

**Comment by chenandrewy** [comment]
Fixed in 52e88fb9ccbff69f6a255ed39b7fa0a356aa0430.  Volume only used to screen observations, so I think the change will be relatively minor, but thank you for catching this @xiaoqyaoyao!
