### ISSUE TITLE
FF csv case doesn't work on linux

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#63]
in 21_PortfolioExhibits.R CSV should be lowercase

**Comment by chenandrewy** [comment]
this commit 423657963f2ef8c26496831a0047c930e94d1ed5 does a quick fix to make csv lowercase, but Sebastian Stockl has a ffdownload package which may do a better job

**Comment by chenandrewy** [comment]
reverted the previous commit to see if @agilderubio can get his setup to do it

**Comment by agilderubio** [comment]
Just pushed edits that fix this issue to patchesAC.

Also, the issue seemed to be exclusive for F-F_Research_Data_5_Factors_2x3.csv. Not F-F_Momentum_Factor.CSV.
