### ISSUE TITLE
Add Drake-Rees-Swanson 2011 (TAR) version of short interest

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#67]
Table 5  trades on double sorts using analyst recommendations and short interest.  This is a "short interest" "risk factor" listed in HLZ that we don't have, exactly.  Some users suggested more short interest stuff.

**Comment by tomz23** [comment]
The OP uses short-interest data from various sources that we do not have access to. We use the monthly CRSP file that has data before 2003 but coverage nearly doubles in mid-2003. Just wanted to check how you feel about adding the signal given that the data sources are different @chenandrewy :

![image](https://user-images.githubusercontent.com/32535583/156631288-cc6f0306-b615-4ccc-80c0-731052412139.png)

**Comment by chenandrewy** [comment]
Hmm, I think you mean we use the _Compustat_ monthly securities file, see [G_CompustatShortInterest.do](https://github.com/OpenSourceAP/CrossSection/blob/d1e4e4d1c08784d2cb8fe1202f772581ec33b66d/Signals/Code/DataDownloads/G_CompustatShortInterest.do).   

You know, I remember having a bit of trouble with the two short interest related predictors we do have.  Perhaps this missing data is part of the reason.  Asquith, Pathak and Ritter also use data that they bought from the exchanges.  Unfortunately, we did not make a note of it in the paper or in SignalDocumentation.xlsx, at least not that I see.  We did categorize these as likely predictors, but that was because one uses only a very small subset of stocks and the other doesn't have a t-stat.  I'll add it to the SignalDocumentation update issue, that we should comment on the poor Compustat coverage there.

I say we drop this predictor.  I have no idea why some data are missing from the Compustat series, and we don't want to cause more confusion.  How does that sound?

**Comment by tomz23** [comment]
Hm, I think given that we include other short-interest predictors with similar data issues, we can include this one as well to be consistent and flag as likely?
Using the Compustat data, I can actually reproduce this one pretty closely with a monthly return of 1.2% and a t-stat of 3.8 (compared to 1.1 and 4.1 in the paper, table 7b).

**Comment by tomz23** [comment]
On second thought, I think it makes more sense to categorize this one as 1_clear but set Signal Rep Quality to 4_lack_data. We did that for some recommendation signals (e.g. `ChangeInRecommendation`) that used Zack's data instead of IBES data, too. Sounds good?

**Comment by chenandrewy** [comment]
That sounds good.  

Dmitriy Muravyev informed me that according to [Byoung-Hyoung Hwang's website](http://www.bhwang.com/code.html) the pre-2003 data is missing most of NASDAQ.  He also said that other papers do go ahead and use the Compustat data despite the missingness.

**Comment by tomz23** [comment]
Sounds good! Added in https://github.com/OpenSourceAP/CrossSection/commit/8fa20199d0391d42b80bf69130e928290112859a
