### ISSUE TITLE
Issues with SignalDocumentation.xlsx

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#68]
I thought I'd create a thread for keeping track of updates needed for SignalDocumentation.xlsx, since git can't track changes in this doc.  Here's a list of issues to start with:

**1.  The detailed description of Accruals has a couple typos.  It now needs depreciation to be subtracted, and is unclear about the parentheses.
2.  The detailed description of AnnouncementReturn has a typo.  It should say 2 days before to 1 day after.**

Both of these are discussed [here](https://github.com/OpenSourceAP/CrossSection/issues/51)

**Comment by chenandrewy** [comment]
A couple things for the to do list
**3. add the TrendFactor signal**
**4. explain the weaknesses of our shortinterest data, see [here](https://github.com/OpenSourceAP/CrossSection/issues/67)

**Comment by tomz23** [comment]
> A couple things for the to do list **3. add the TrendFactor signal** **4. explain the weaknesses of our shortinterest data, see [here](https://github.com/OpenSourceAP/CrossSection/issues/67)**

`TrendFactor` and `Recomm_ShortInterest` added to SignalDocumentation in https://github.com/OpenSourceAP/CrossSection/commit/8fa20199d0391d42b80bf69130e928290112859a

**Comment by chenandrewy** [comment]
@tomz23: Should we convert this xlsx file to csvs so we can track changes in Github?  Seems like that's the best thing for the long term though it'll take a bit of work now.

**Comment by chenandrewy** [comment]
Coverted SignalDocumention.xlsx to SignalDoc.csv (with info for all signals in our data), Comparison_to_MetaReplications.csv, and Comparison_to_HLZ.csv (since it's not as straightforward to compare) here:

a7b6c5ca41048f298881f8144bb5a35982d0e578

Still need to add the suggested documentation above.

**Comment by chenandrewy** [comment]
Documentation changes finished here:  ad8481ce2a1f4fe95a7be0592b8d1057dbb1c64e
