### ISSUE TITLE
Manual download - sources

### ISSUE THREAD

**Issue by choegner** [OpenSourceAP/CrossSection#7]
In your project you have mainly two datasets needing manual download:

|---- Calls 12_PrepareOtherData.do
      |---- Uses pin1983-2001.dat which is currently not being downloaded automatically
      |---- Uses SinStocksHong.xlsx which is currently not being downloaded automatically

Could you please indicate from which sources you downloaded the two files and whether they are publicly available?

Thanks for the great project!

**Comment by OpenSourceAP** [comment]
Good suggestion! Let me add direct downloads to the code. The PIN data are from here: https://sites.google.com/site/hvidkjaer/data
The SinStocksHong file is from the pdf on Hong's website: http://www.columbia.edu/~hh2679/sinstocks.pdf

**Comment by OpenSourceAP** [comment]
Updated in commit https://github.com/OpenSourceAP/CrossSection/commit/ff7e7c16a33e689d18c2fe591d7c63daa9a2c3c4
