### ISSUE TITLE
Use of permno for stock identification is not open (as far as I can tell)

### ISSUE THREAD

**Issue by colintbowers** [OpenSourceAP/CrossSection#74]
Hi. This paper/code/data is a wonderful idea, so thanks for your work on it. I thought I'd file this issue to raise the point that CRSP permno is not an open standard (I don't think), so anyone whose institution does not have a subscription (my own only has Refinitiv) will be unable to use your individual security data, given that it appears to use permno as the identifier, rather than an open standard (such as CUSIP). It is possible that using permno's was a condition of publication of the data. If so, I perfectly understand that your hands are tied and that is that. But I thought I'd check, just in case :-)

EDIT: If allowed, an additional csv file mapping permno to cusip for the securities in question would deal with this

Cheers,

Colin

**Comment by chenandrewy** [comment]
@colintbowers, thanks for the comment.  There are certainly limits to open source data, and I think this is one of them.  I wouldn't feel comfortable posting security link tables.

**Comment by colintbowers** [comment]
Fair enough @chenandrewy. Thanks for taking the time to respond. Cheers -Colin
