### ISSUE TITLE
typo in signal file

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#81]
Sheet **HXZ** in `OldSignalDocumentation.xlsx`:
|Number|HXZname|
|---|---|
|182|Rna16|

The name should be **Rnaq6**

And `Comparison_to_MetaReplications.csv` needs to be updated by re-running the r script.

**Comment by chenandrewy** [comment]
fixed here: 7d4fcda6aee12c965930d5e3320e78114fa78d93

**Comment by chenandrewy** [comment]
It turns out we should not have been keeping around the old conversion script and I should have edited the comparisons csv directly.  I cleaned up in the commit here: cf3faca6ecc87400c608e8526a9213a1d5387363

**Comment by chenandrewy** [comment]
OK fixed properly here: 69865cf0d2207a496ff3beaff921a2992df2cf4a
