### ISSUE TITLE
Better OptionMetrics - CRSP link

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#83]
Right now we link by ticker-month and keep the obs with the highest volume.  Zhongjin (Gene) Lu suggested that we use [WRDS Macro: OCLINK (upenn.edu)](https://wrds-www.wharton.upenn.edu/pages/support/research-wrds/macros/wrds-macro-oclink/) instead.

**Comment by AlecErb** [comment]
Now merging on 'secid' from WRDS OCLink SAS macro. Implemented in OptionVolume1.do, OptionVolume2.do, skew1.do, smileslope.do, cpvolspread and rivolspread
