### ISSUE TITLE
ep.do negative ib filter

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#86]
a close read of Table 1 of Basu 1977 implies removing negative ib is not necessary: 

![image](https://user-images.githubusercontent.com/65506481/166128318-34005b93-c47e-4b0a-8849-c2521ad45b1b.png)

**Comment by tomz23** [comment]
Are you suggesting to create two versions of EP? @chenandrewy

**Comment by chenandrewy** [comment]
No, just that we use as many stocks as possible while being consistent with OP.

**Comment by chenandrewy** [comment]
I say we stick with the current code then.  It seems like the remaining discrepancy is because Basu only lags earnings data by 3 months: 
![image](https://github.com/OpenSourceAP/CrossSection/assets/65506481/90164b07-71a0-4554-8d2d-bf7c440715a2)

But we don't want to go there, so please go ahead and close this issue.
