### ISSUE TITLE
clearly document timing of the data (not a code issue)

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#87]
I was asked "I am trying to use the anomaly data based on the data in your paper “Open Source Cross-Sectional Asset Pricing.” I have one clarification question: in the data, the date is in the following format: “1986m1.” Should I assume it was based on the end or beginning of Jan in 1986?"   We should post the answer clearly somewhere.

**Comment by iProdigy** [comment]
Could add a FAQ page in [the wiki](https://github.com/OpenSourceAP/CrossSection/wiki) (and possibly link to it from the readme)

**Comment by chenandrewy** [comment]
Actually, we have a FAQ at the data / news page https://www.openassetpricing.com/faq/, and I was thinking of posting it there.  

But thanks for pointing out that we should link clearly to the FAQ on github.com.   Perhaps the data page should be linked more prominently too.

**Comment by tomz23** [comment]
Added to the FAQ here: https://www.openassetpricing.com/faq/#q-timing

**Comment by tomz23** [comment]
Added link to FAQ to readme in https://github.com/OpenSourceAP/CrossSection/commit/d92fffbf18e43f3974505632e5f71ca01ac06fd5
