### ISSUE TITLE
Typos in Net-Debt-Finance, Net-Equity-Finance, Net-External-Finance

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#88]
A helpful doctoral student writes:

> Hi Mr. Chen, 
> 
> my name is Julian Böll, I am a doctoral student from Karlsruhe Institute of Technology in Germany and a big fan of your Open Asset Pricing project.
> 
> For our research project, I am currently replicating the majority of asset pricing anomalies myself and use the results of HXZ and Open Asset Pricing as sanity checks. In the process I stumbled across some inconsistencies in your code regarding the above mentioned anomalies.
> 
> Bradshaw, Richardson, Sloan (2006) write on page 9: "∆XFIN = ∆EQUITY + ∆DEBT. ∆EQUITY represents net cash received from the sale (and/or purchase) of common and preferred stock less cash dividends paid (COMPUSTAT annual data item 108 less COMPUSTAT annual data item 115 less COMPUSTAT annual data item 127). ∆DEBT represents net cash received from the issuance (and/or reduction) of debt (COMPUSTAT annual data item 111 less COMPUSTAT annual data item 114 plus COMPUSTAT annual data item 301).” 
> 
> Now your code from the GitHub site:
>  
>  
>  
> 
> 1. In the NetEquityFinance line Compustat Item 127 “DV” is missing.
> 2. In the NetDebtFinance line you are subtracting “DLCCH" instead of adding it up.
> 3. In the XFIN line “DV" suddenly appears but “DLCCH" suddenly disappears.
> 
> These are just minor adjustments and the results should mostly stay the same, but I wanted to point them out nevertheless in order to support your open source project.
> 
> Kind regards from Germany,
> Julian Böll
>

**Comment by lena-will** [comment]
fixed in "Typos in Net-Debt-Finance, Net-Equity-Finance, Net-External-Finance"

**Comment by tomz23** [comment]
Fixed here https://github.com/OpenSourceAP/CrossSection/pull/129/commits/f097c04d0e61c2aad062659cdcce061976bf0328
