### ISSUE TITLE
WRDS_DL_IBES.sas

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#9]
I am not able to run `WRDS_DL_IBES.sas` without including the location of SAS macro:
```
%include '/wrdslin/wrdsmacros/iclink.sas';
```

**Comment by matiarj** [comment]
I found iclink on wrds it's a macro they made just search it in the search bar.

**Comment by mk0417** [comment]
@matiarj , I mean we need to add this line in `WRDS_DL_IBES.sas`: 
```
%include '/wrds/wrdsmacros/iclink.sas';
%ICLINK (IBESID=IBES.ID,CRSPID=CRSP.STOCKNAMES,OUTSET=WORK.ICLINK);
```

You should set up `autoexec.sas` in your WRDS server home folder if you do not want to import the macro when you call the macro. Two lines are needed in `autoexec.sas`:
```
%include '/wrds/lib/utility/wrdslib.sas';
options sasautos=('/wrds/wrdsmacros/', SASAUTOS) MAUTOSOURCE;
```

If you can run `WRDS_DL_IBES.sas` without importing the macro, I think you have the two lines already.

**Comment by OpenSourceAP** [comment]
Connection to WRDS server addressed in updated readme and SAS downloads updated in Signals/Code/PrepScripts with documentation in d1e4e4d1c08784d2cb8fe1202f772581ec33b66d
