### ISSUE TITLE
IBES-related missing values in 2022 revision?

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#90]
Yufeng Han (UNCC) writes: 

> In an effort to update the date we try to use your most recent data and found there are some differences between the new and old data. We used your 2020 data and try to update to your 2022 data, but some of the variables have more missing value in the new data than in the old data. I didn’t do an extensive comparison but just notice, for example, sfe and aop used to have more values for say permno 10000 in the 2020 data but now are all missing in the 2022 data. Do you have an explanation for this?

Both sfe and aop use ibes data.  Perhaps there is an ibes linking issue in the 2022 update?

**Comment by mk0417** [comment]
Hi @chenandrewy,

This might not be the linking problem. I had a check `sfe` of permno **10001** (ibes ticker **GFGC**). 

**Signals/Code/Predictors/sfe.do**
```
keep if fpi == "1" & month(statpers) == 3 // OP uses march forecasts

keep if fpedats != . & fpedats > statpers + 90 // keep only forecasts past June
```
After the above two filters, this is the observations from IBES. We can see that there are no `medest` from 2002 to 2015.

<img width="829" alt="ibes" src="https://user-images.githubusercontent.com/27696880/173708188-2d5d37d7-8a24-4a70-8918-61b0749356f7.png">

Futher, after adding the condition below, there should be no values before 2007. So the values of `sfe` in the latest version is from 201603 to 201802 
```
* only dec fyr ends
keep if month(datadate) == 12
```
<img width="334" alt="comp" src="https://user-images.githubusercontent.com/27696880/173708264-95a421a8-0c2f-45dd-bbf6-36caefbdde69.png">

**Comment by chenandrewy** [comment]
Thanks @mk0417 for helping look into this!  

There is no issue with linking, or with the code as far as I can tell.  It seems that Yufeng Han was previously using data based on v0.1.2, and v1.0.0 and later included many more screens to match the text in the original papers.  

Between these two code versions sfe had the following screen added:
 
![image](https://user-images.githubusercontent.com/65506481/173833169-6d83b707-5679-422d-9339-8e84321a6d9d.png)

We added this screen because, based on our reading, Elgers, Lo, and  Pfeiffer only found predictability in low analyst coverage stocks:

![image](https://user-images.githubusercontent.com/65506481/173833253-d94bbb7a-3fa1-4d59-88bc-7e935e36aa3f.png)

It's worth noting that the Chen-Zimmermann strategies don't do size adjustment, as is done in the Elgers-Lo-Pfeiffer table.

AOP seems to have some new screens too:
 
![image](https://user-images.githubusercontent.com/65506481/173833442-76e1c9cc-70db-4e4a-90ba-3736c903675b.png)

I'm closing this issue since it seems to be tracked down now and as far as I can tell the missing values needed to try to match the original findings.
