### ISSUE TITLE
some more typos in KZ.do and KZ_q.do

### ISSUE THREAD

**Issue by ju-kit** [OpenSourceAP/CrossSection#92]
Hi guys,

its Julian from Karlsruhe in Germany again.

Found some more typos in your code. This time it is the KZ index, file KZ.do and KZ_Q.do, in placebos.

OP calculates KZ on page 552 according to:
-1.001909* [(Item 18 + Item 14)/ Item 8] +.2826389* [(Item
 6 + CRSP December Market Equity - Item 60 -Item 74)/ Item 6] +3.139193* [(Item 9+Item
 34) / (Item 9+Item 34 + Item 216)] -39.3678* [(Item 21 + Item 19)/Item 8] -1.314759*
 [Item 1/Item 8

You calculate KZ according to: 
KZ = -1.002* (ib + dp)/at  ///
	+ .283*(at + mve_c - ceq - txdb)/at ///
	+ 3.319*(dlc + dltt)/(dlc + dltt + seq) ///
   - 39.368*((dvc+dvp)/at) - 1.315*(che/at)

First: you use item 6 (at) instead of item 8 (ppent) on multiple occasions. Is that on purpose?
Second: you have a typo in the coefficient. You type 3.319 but it should be 3.139

Again, just minor stuff. But its all about the little things in life, right!

Take care,
Julian

**Comment by chenandrewy** [comment]
@ju-kit, this is super helpful.   We want to make sure everything is as close to the OPs as possible so we'll fix this.

**Comment by lena-will** [comment]
fixed in "fix some more typos in KZ.do and KZ_q.do"
