### ISSUE TITLE
Rev6 has very few observations

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#94]
Even in recent data, Rev6 is observed for only 10% of stocks 
![image](https://user-images.githubusercontent.com/65506481/178617161-7e07f528-269f-486a-bf26-d0ec5f79fbc4.png)

Rev6 is just the 6-month moving average of eps forecast changes scaled by the most recent stock price.  It shouldn't be missing this much, should it?

**Comment by tomz23** [comment]
The issue can be traced to this line
`keep if fpedats != . & fpedats > statpers + 30`

that drops observations very close to the forecast period end date. The panel is then very imbalanced, and the six-month lag cannot be calculated properly:

`gen REV6 = tempRev + l.tempRev + l2.tempRev + l3.tempRev + l4.tempRev + l5.tempRev + l6.tempRev`

I instead kept the observations but carried forward the last EPS forecast that happened at least 30 days ago, see 17c6578deeaa06e74b21b52925d5f4f75bcc4915 

Does this sound good to you @chenandrewy ?

If so, feel free to close the issue.

**Comment by chenandrewy** [comment]
Sorry for the slow response.  Your fix sounds good!  Thanks!
